#!/bin/bash

dir="$(dirname "$0")"

source $dir/python/third-party/py3
source $dir/python/third-party/py2
source $dir/python/third-party/data_anal


# Install 
function py_pck {
	eval `resize`
	THIRDPARTY=$(whiptail \
		--notags \
		--title "Python Installation" \
		--menu "\nWhat do you want to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		'py3' 'Install Python3 and pip3' \
		'py2' 'Install Python2 and pip2' \
		'data_anal' 'Data Analyst: Numnpy, Pandas, SkLearn' \
		3>&1 1>&2 2>&3)
	 
	exitstatus=$?
	if [ $exitstatus = 0 ]; then
		$THIRDPARTY
	else
		main
	fi
}
