#!/bin/bash

# spark
function spark {
	# Variables
	PACKAGE=spark
	NAME="spark"
	VERSION="2.1"
	# Install
	show_header 'Begin '$NAME' installation'
	# Check if already installed
	#show_info 'Checking if '$NAME' already installed...'
	#PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
	
	if [ "" == "$PKGCHECK" ]; then
		echo $NAME 'is not installed. Proceeding'
		show_info 'Downloading '$NAME' version $VERSION...'
		wget http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz
		# Install package(s)
		show_info 'Installing '$NAME'...'
		show_warning 'Requires root privileges'
		sudo tar xvf spark-2.1.0-bin-hadoop2.7.tgz  -C /usr/local
		sudo ln -s /usr/local/spark-2.1.0-bin-hadoop2.7 /usr/local/spark
		grep -q -F 'export SPARK_HOME' ~/.bashrc || echo 'export SPARK_HOME=/usr/local/spark' >> ~/.bashrc
		#echo 'export SPARK_HOME=/usr/local/spark-2.1.0-bin-hadoop2.7' >> ~/.bashrc 
		echo 'export PATH=$SPARK_HOME/bin:$SPARK_HOME:$PATH' >> ~/.bashrc 
		echo 'export PYTHONPATH=$SPARK_HOME/python:$PYTHONPATH' >> ~/.bash
		rm park-2.1.0-bin-hadoop2.7.tgz
		# Cleanup and finish
		# Done
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		ml
	else
		# Already installed
		show_success $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		ml
	fi
}
