#!/bin/bash

# spark
function spark {
	# Variables
	PACKAGE=spark
	NAME="spark"
	VERSION="1.6"
	# Install
	show_header 'Begin '$NAME' installation'
	# Check if already installed
	#show_info 'Checking if '$NAME' already installed...'
	#PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
	
	if [ "" == "$PKGCHECK" ]; then
		echo $NAME 'is not installed. Proceeding'
		show_info 'Downloading '$NAME' version $VERSION...'
		wget http://d3kbcqa49mib13.cloudfront.net/spark-1.6.0.tgz
		# Install package(s)
		show_info 'Installing '$NAME'...'
		show_warning 'Requires root privileges'
		sudo tar xvf spark-1.6.0.tgz
		cd spark-1.6.0
		sbt/sbt assembly
		# Cleanup and finish
		rm spark-1.6.0.tgz
		# Done
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		ml
	else
		# Already installed
		show_success $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		ml
	fi
}
